export const GENRES = [
  {
    id: 0,
    name: "Todos los géneros",
    generos: [
      { name: "Acción", id: 28 },
      { name: "Animados", id: 16 },
      { name: "Documentales", id: 99 },
      { name: "Drama", id: 18 },
      { name: "Familiar", id: 10751 },
      { name: "Fantasía", id: 14 },
      { name: "Historia", id: 36 },
      { name: "Comedia", id: 35 },
      { name: "Guerra", id: 10752 },
      { name: "Crimen", id: 80 },
      { name: "Música", id: 10402 },
      { name: "Misterio", id: 9648 },
      { name: "Romance", id: 10749 },
      { name: "Sci-fi", id: 878 },
      { name: "Horror", id: 27 },
      { name: "TV pelis", id: 10770 },
      { name: "Thriller", id: 53 },
      { name: "Western", id: 37 },
      { name: "Aventura", id: 12 },
    ],
  },
];
